### ISSUE TITLE
在直播加载过程中退出直播，会导致闪退，log如下:

### ISSUE THREAD

**Issue by wxwxwz** [h4de5ing/takagen99-TVBoxOSC#1]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.tvbox.osc.tk, PID: 6154
    java.lang.NullPointerException: Attempt to invoke virtual method 'void xyz.doikki.videoplayer.player.VideoView.setPlayerFactory(xyz.doikki.videoplayer.player.PlayerFactory)' on a null object reference
        at com.github.tvbox.osc.util.PlayerHelper.updateCfg(PlayerHelper.java:74)
        at com.github.tvbox.osc.bean.LivePlayerManager.getDefaultLiveChannelPlayer(LivePlayerManager.java:36)
        at com.github.tvbox.osc.bean.LivePlayerManager.init(LivePlayerManager.java:32)
        at com.github.tvbox.osc.ui.activity.LivePlayActivity.initLiveState(LivePlayActivity.java:1568)
        at com.github.tvbox.osc.ui.activity.LivePlayActivity.access$4200(LivePlayActivity.java:91)
        at com.github.tvbox.osc.ui.activity.LivePlayActivity$28.lambda$onSuccess$0$com-github-tvbox-osc-ui-activity-LivePlayActivity$28(LivePlayActivity.java:1516)
        at com.github.tvbox.osc.ui.activity.LivePlayActivity$28$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6635)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
E/MQSEventManagerDelegate: failed to get MQSService.
I/Process: Sending signal. PID: 6154 SIG: 9

**Comment by h4de5ing** [comment]
> E/AndroidRuntime: FATAL EXCEPTION: main Process: com.github.tvbox.osc.tk, PID: 6154 java.lang.NullPointerException: Attempt to invoke virtual method 'void xyz.doikki.videoplayer.player.VideoView.setPlayerFactory(xyz.doikki.videoplayer.player.PlayerFactory)' on a null object reference at com.github.tvbox.osc.util.PlayerHelper.updateCfg(PlayerHelper.java:74) at com.github.tvbox.osc.bean.LivePlayerManager.getDefaultLiveChannelPlayer(LivePlayerManager.java:36) at com.github.tvbox.osc.bean.LivePlayerManager.init(LivePlayerManager.java:32) at com.github.tvbox.osc.ui.activity.LivePlayActivity.initLiveState(LivePlayActivity.java:1568) at com.github.tvbox.osc.ui.activity.LivePlayActivity.access$4200(LivePlayActivity.java:91) at com.github.tvbox.osc.ui.activity.LivePlayActivity$28.lambda$onSuccess$0$com-github-tvbox-osc-ui-activity-LivePlayActivity$28(LivePlayActivity.java:1516) at com.github.tvbox.osc.ui.activity.LivePlayActivity$28$$ExternalSyntheticLambda0.run(Unknown Source:2) at android.os.Handler.handleCallback(Handler.java:794) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:176) at android.app.ActivityThread.main(ActivityThread.java:6635) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) E/MQSEventManagerDelegate: failed to get MQSService. I/Process: Sending signal. PID: 6154 SIG: 9

ok,我看一下。

**Comment by wxwxwz** [comment]
再者就是源码编译后，请求存储权限闪退，给权限数据备份恢复失效，我看你隐藏的主题功能正常

**Comment by wxwxwz** [comment]
![Screenshot_20230213-191952](https://user-images.githubusercontent.com/56331159/218444394-148f30b9-5a31-4053-8eb8-e321c8f28a6f.png)
![Screenshot_20230213-191929](https://user-images.githubusercontent.com/56331159/218444409-c8f05d51-8f63-45a6-a314-d8b56e5ee048.png)
